name: Semantic Release

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v2
      with:
       semantic_version: 17.1.1
      id: semantic   # Need an `id` for output variables
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}        
    - name: Do something when a new release published
      if: steps.semantic.outputs.new_release_published == 'true'
      run: |
        echo ${{ steps.semantic.outputs.new_release_version }}
        echo ${{ steps.semantic.outputs.new_release_major_version }}
        echo ${{ steps.semantic.outputs.new_release_minor_version }}
        echo ${{ steps.semantic.outputs.new_release_patch_version }}
